---
abstract: 'Arbitrary big rational numbers'
author:
  - '(C) by Tels L<http://bloodgate.com/> 2001 - 2009., Peter John Acklam <pjacklam@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-BigRat
no_index:
  directory:
    - t
    - inc
requires:
  Math::BigInt: '1.991'
  perl: '5.006'
version: '0.260802'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
