---
abstract: 'Arbitrary big rational numbers'
author:
  - '(C) by Tels L<http://bloodgate.com/> 2001 - 2009.'
  - 'Jonathan Leto <jonathan@leto.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BigRat
no_index:
  directory:
    - inc
    - t
requires:
  Math::BigInt: 1.88
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.26
